# See https://medium.com/@princehari.selvaraj/deploy-kong-gateway-on-docker-08fa02111582
version: '3.7'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - kong-db-data:/var/lib/postgresql/data  # Persist DB data
  
  kong-gateway:
    image: kong/kong-gateway:3.7.1.2
    container_name: kong-gateway
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database  # Name of the PostgreSQL container
      KONG_PG_USER: kong           # Username for PostgreSQL
      KONG_PG_PASSWORD: kongpass   # Password for PostgreSQL
     
      KONG_ADMIN_LISTEN: 0.0.0.0:8001  # Admin API
      KONG_ADMIN_GUI_URL: http://localhost:8002  # Admin GUI URL
    depends_on:
      - kong-database  # Ensure Kong waits for PostgreSQL to start
    ports:
      - "8000:8000"   # Proxy API port
      - "8443:8443"   # Proxy API HTTPS port
      - "8001:8001"   # Admin API port
      - "8444:8444"   # Admin API HTTPS port
      - "8002:8002"   # Admin GUI port
      - "8445:8445"   # Admin GUI HTTPS port
#    command: kong migrations bootstrap  # Run migrations on startup
    restart: on-failure  # Restart in case of failure

networks:
  kong-net:
    driver: bridge

volumes:
  kong-db-data: {}  # Named volume to persist database data
