# See https://medium.com/@manzurulhoque/implementing-kong-api-gateway-for-microservices-1a4a85303102
version: '3.8'

services:
  kong:
    image: kong/kong-gateway:3.8.0.0
    container_name: kong
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "7000:8000"    # Proxy
      - "7443:8443"    # Proxy (SSL)
      - "8001:8001"    # Admin
      - "7002:8002"    # GUI
      - "7444:8444"    # Admin (SSL)
    environment:
      - KONG_DATABASE=off       # Disable database mode
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml # Use kong.yml for configuration
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:7002
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - food-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7001/" ]
      interval: 30s
      timeout: 10s
      retries: 3